version: '3.2'

services:
  postgres:
    image: postgres
    env_file:
      - db.env
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    networks:
      - network

  postgres_test:
    image: postgres
    env_file:
      - db_test.env
    ports:
      - '6000:5432'
    volumes:
      - ./db_test:/docker-entrypoint-initdb.d

    networks:
      - test_network

  app:
    build:
      context: ./src/.
    env_file:
      - .env
    volumes:
      - ./src/images:/images

    ports:
      - '8000:8000'
    depends_on:
      - postgres

    networks:
      - network

  app_test:
    build:
      context: ./src/.
      dockerfile: Dockerfile_test

    env_file:
      - .env
    command: sh -c 'python -m pytest -s -vv'
    depends_on:
      - postgres_test
      - app
    networks:
      - test_network
    ports:
      - '8001:8000'

  nginx:
    build:
      context: ./nginx/.
    ports:
      - '8080:80'
    volumes:
      - ./src/images:/usr/share/nginx/html/static/images

    depends_on:
      - app
    networks:
      - network

networks:
    network:
        driver: bridge
    test_network:
        driver: bridge

